### PR TITLE
Tip for MIR_new_func_arr

### PR DESCRIPTION
**Pull request by iacore**
MIR_new_func_arr sets `vars[i].name` to the allocated name (which may be different from the chosen name)

see the diff

### CODE REVIEW

**Comment by giann** [comment]
Yes. Still weird though.
I'll merge this once i get to updating things for latest zig build.
I the middle of rewriting the ast and everything using it right now.

**Comment by giann** [comment]
@iacore turns out that fix does not work, I had to revert to the previous (ugly) usage

**Comment by iacore** [comment]
Interesting! Did MIR update?

**Comment by giann** [comment]
No it just did not work

**Pull request closed without merging**
